version: "3.9"

services:
  db:
    image: postgres:15-alpine3.17
    container_name: univer-db
    stdin_open: true
    tty: true
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.db

  app:
    build: ./app
    container_name: univer-app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.app
    depends_on:
      - db

volumes:
  postgres_data:
